services:
  - type: web
    name: appointment-booking-api
    env: python
    rootDir: appointment-booking-api/src
    buildCommand: ""
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
